@startmindmap
* Quality
** 1.Perfomance
*** Capacity
****_: ...
;

** 2.Relability 
*** Availability
****_: ...
;
****_: ...
;
****_: ...
;

** 3. Compatibility
*** Interoperability
****_: ...

;
** 4. Functional Suitability

*** Functional appropriateness

****_: ....
;

** 5. Portability

*** Adaptability

****_: ....
;

@endmindmap