@startuml
title Sequence diagram for sending a message
participant main  as main
participant "rclpp" as rcpp_p
participant "MinimalPublisher : public rclcpp::Node" as node
participant publisher
autonumber 
main->rcpp_p: init()
create node
main-> node:create
node->node: create_publisher()
create publisher
node->publisher:
node->node: create_wall_timer()
main->rcpp_p :spin
loop
rcpp_p->node:execute()
end
group timer expires
node->>node: timer_callback()
create message
node->message : new Message("Hello, world!") 
node->publisher:publish(message)
end
@enduml
